# Generated by Django 3.1.7 on 2022-01-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_review_user'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
