# Generated by Django 3.1.7 on 2021-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800)),
                ('author_first_name', models.CharField(max_length=50)),
                ('author_second_name', models.CharField(max_length=50)),
            ],
        ),
    ]
