# Generated by Django 3.1.7 on 2022-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220109_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=50)),
                ('author_second_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
