# Generated by Django 3.1.7 on 2022-01-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220109_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_second_name',
        ),
    ]
