# Generated by Django 3.1.7 on 2022-01-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211221_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
